Chore/adr css
juansalinas-xyz/greenplus-adrs pull request #2
Opened 2024-01-27 19:18 UTC by DBrange

Reemplazo de todo el texto a ingles.

2024-01-29 19:52 UTC, DBrange commented
Agrego archivo de adr para analizar provedor de notificaciones

2024-01-29 20:23 UTC, juansalinas-xyz requested changes

2024-01-29 20:23 UTC, juansalinas-pro commented on docs/adr/001-CSS-framework
> +## Context
El titulo debe ser: ## Context and Problem Statement

2024-01-29 20:23 UTC, juansalinas-pro commented on docs/adr/002-Email-API
> +## Context
El titulo debe ser: ## Context and Problem Statement

2024-01-29 20:23 UTC, juansalinas-xyz commented on docs/adr/002-Email-API
> +# CSS Framework
El titulo debe ser: Notifications provider

2024-01-29 20:51 UTC, DBrange commented on docs/adr/002-Email-API
> +# CSS Framework
Los proveedores se redujeron a 3, se corrigieron el título y el contexto y se agregó nueva información.

2024-01-29 20:54 UTC, DBrange commented
Los proveedores se redujeron a 3, se corrigieron el título y el contexto y se agregó nueva información.

2024-01-29 21:49 UTC, juansalinas-xyz commented
@DBrange  Falta la sección de ## Decision Drivers en ambos archivos.

2024-01-29 21:51 UTC, juansalinas-xyz commented
@DBrange en el ADR de Framework de CSS falta cambiar el titulo de Context a ## Context and Problem Statement

2024-01-29 23:37 UTC, DBrange commented
Added decision drivers and changed the title from “Context” to “Context and Problem Statement.”

2024-01-30 00:15 UTC, DBrange commented
Added material-ui to options

2024-01-30 00:32 UTC, merged